/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import models.Task;
import models.TaskDAO;

/**
 *
 * @author workplz
 */
public class main extends javax.swing.JFrame {

    private List<Task> task = null;
    private boolean editMode = false;
    private JPopupMenu popup;
    private JMenuItem menuItem, menuItem2, menuItem3, menuItem4;

    /**
     * Creates new form main
     */
    public main() {
        // super method
        super("To do list..");
        // properties/methods that effect view
        this.setVisible(true);
        this.setResizable(false);
        this.isAlwaysOnTop();
        // back-end methods
        initComponents();
        tasks();
    }

    public void tasks() {

        if (editMode) {
            popup = new JPopupMenu();

            menuItem = new JMenuItem("Delete");
            menuItem2 = new JMenuItem("menu-item");
            menuItem3 = new JMenuItem("menu-item");
            menuItem4 = new JMenuItem("menu-item");

            popup.add(menuItem);
            popup.add(menuItem2);
            popup.add(menuItem3);
            popup.add(menuItem4);
        }

        try {
            TaskDAO t = new TaskDAO();
            task = t.readAllTasks();
            fillTable(task);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void fillTable(List<Task> list) {

        this.task = list;

        for (int x = 0; x < 39; x++) {
            jTable2.getModel().setValueAt("", x, 0);
            jTable2.getModel().setValueAt("", x, 1);
            jTable2.getModel().setValueAt("", x, 2);
        }

        for (int i = 0; i < task.size(); i++) {
            if (i < 39) {

                jTable2.getModel().setValueAt(task.get(i).getVoor(), i, 0);
                jTable2.getModel().setValueAt(task.get(i).getWat(), i, 1);
                jTable2.getModel().setValueAt(task.get(i).getWaneer(), i, 2);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        JMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jTable2.setBackground(new java.awt.Color(204, 255, 255));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Voor", "Wat", "Waneer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setEnabled(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jMenu1.setText("File");
        jMenu1.setToolTipText("");
        jMenu1.setContentAreaFilled(false);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1389753904_plus-24.png"))); // NOI18N
        jMenuItem1.setText("Add");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1380635235_exit.png"))); // NOI18N
        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        JMenu2.setText("Edit");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1389766153_85.png"))); // NOI18N
        jMenuItem5.setText("Turn edit mode on..");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        JMenu2.add(jMenuItem5);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1389764123_trash.png"))); // NOI18N
        jMenuItem3.setText("Empty all tasks");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        JMenu2.add(jMenuItem3);

        jMenuBar1.add(JMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        addTask a = new addTask();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        tasks();
    }//GEN-LAST:event_formWindowGainedFocus

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        TaskDAO t = new TaskDAO();
        try {
            t.empty();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (!editMode) {
            editMode = true;
            jMenuItem5.setText("Turn edit mode off..");

            // edit mode enables table editing
            jTable2.setEnabled(editMode);
            tasks();

        } else {
            editMode = false;
            jMenuItem5.setText("Turn edit mode on..");

            // disable table from being edited
            jTable2.setEnabled(editMode);
            jTable2.clearSelection();
            tasks();
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        addTask a;
        TaskDAO t = new TaskDAO();
        int tempId;


        // delete method on right-click


        if (evt.getButton() == evt.BUTTON3) {
            int[] s = jTable2.getSelectedRows();

            System.out.println("Length: " + s.length);
            if (s.length > 1) {
                int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete all these records? ", "Warning!", JOptionPane.YES_NO_OPTION);
                if (i == JOptionPane.YES_OPTION) {

                    for (int sPart : s) {
                        if (sPart < task.size()) {
                            try {
                                System.out.println("----");
                                System.out.println("Part : " + sPart);
                                System.out.println("ID : " + task.get(sPart).getId());
                                System.out.println("----");
                                t.deleteTask(task.get(sPart).getId());



                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }

                        jTable2.clearSelection();
                    }
                }
            } else {

                if (editMode) {
                    if (jTable2.rowAtPoint(evt.getPoint()) < task.size()) {
                        tempId = task.get(jTable2.rowAtPoint(evt.getPoint())).getId();
                        int i = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete \"" + task.get(jTable2.rowAtPoint(evt.getPoint())).getWat() + "\"", "Warning!", JOptionPane.YES_NO_OPTION);

                        if (i == JOptionPane.YES_OPTION) {
                            System.out.println("Yes'd");
                            try {
                                t.deleteTask(tempId);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        } else {
                            System.out.println("No'd");
                        }
                    } else {
                        // other code for outside of rows, maybe add tasks through right-click?
                        System.out.println("Out of row count...");
                    }
                }
            }

            if (evt.getButton() == evt.BUTTON1) {
                if (editMode) {
                    if (jTable2.getSelectedRow() < task.size()) {
                        a = new addTask(task.get(jTable2.getSelectedRow()));
                        a.setLocationRelativeTo(null);
                        a.setVisible(true);

                    }
                }
            }
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu JMenu2;
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JMenuItem jMenuItem5;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable1;
    public javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
